### ISSUE TITLE
Sentry Gradle Configurations failing gradle sync with v2.0.0-alpha.3

### ISSUE THREAD

**Issue by nglazkov** [getsentry/sentry-android-gradle-plugin#113]
_Android Gradle Plugin:_
**4.2.1**

_Gradle:_
**6.7.1**

_Optimizer:_
- [ X ]  R8

_Have you created the sentry.properties file?_
- [ X ]  Yes -> root

_SDKs:_
- [ X ]  sentry-android -> 2.0.0-alpha.3

---
I have the following issue:

I can't perform gradle sync if I have any [Sentry Gradle Configurations](https://docs.sentry.io/platforms/android/proguard/#gradle-configuration).
For example:
```
sentry {
    autoUpload true
}
```
For latest stable version 1.7.36 it is working fine.
I'm updated the version because in some releases, my logs are obfuscated even if the proguard mapping is present in the sentry.io
And when I open the issue report I see the message:

> There was 1 error encountered while processing this event
>Some frames appear to be minified. Did you configure the Sentry Gradle Plugin?

I guess that this issue might be related to https://github.com/getsentry/sentry-android-gradle-plugin/issues/37

**Steps to reproduce:**
- Just add any sentry gradle configuration and try to sync

**Actual result:**
- Gradle sync fails with something like:
> Caused by: groovy.lang.MissingMethodException: No signature of method: build_xxx.android() is applicable for argument types: (build_xxx$_run_closure1) values: [build_xxx$_run_closure1@xxx]

- If I don't put any sentry gradle configs, sync is done successfully

**Expected result:**
- sucessfull gradle sync

**Comment by marandaneto** [comment]
https://docs.sentry.io/platforms/android/migration/#migrating-from-iosentrysentry-android-gradle-plugin-1x-to-iosentrysentry-android-gradle-plugin-200

**Comment by marandaneto** [comment]
please follow the migration guideline, once it's stable, we're gonna change the docs, thanks

**Comment by mkilmanas** [comment]
I am on AGP 7.0.2 / Gradle 7.0.2 and when I try to upgrade sentry-android-gradle-plugin from 1.7.36 to 2.1.4 I get exactly this very same problem
> org.gradle.api.GradleScriptException: A problem occurred evaluating project ':app'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
	...
Caused by: groovy.lang.MissingMethodException: No signature of method: build_5k69o531q003o3za7vyny51vi.sentry() is applicable for argument types: (build_5k69o531q003o3za7vyny51vi$_run_closure3) values: [build_5k69o531q003o3za7vyny51vi$_run_closure3@76bf7f3a]
Possible solutions: every(), every(groovy.lang.Closure), any(), sync(org.gradle.api.Action), any(groovy.lang.Closure), identity(groovy.lang.Closure)
	at build_5k69o531q003o3za7vyny51vi.run
	
the issue points to the app/build.gradle file line where `sentry {` is placed. If I remove the sentry section, then it syncs w/o problems.

I have followed both [the migration instructions](https://docs.sentry.io/platforms/android/migration/#migrating-from-iosentrysentry-android-gradle-plugin-1x-to-iosentrysentry-android-gradle-plugin-200) as well as [latest documentation](https://docs.sentry.io/platforms/android/proguard/#gradle-configuration).

Is this still not solved, or what am I missing?

**Comment by cortinico** [comment]
> the issue points to the app/build.gradle file line where `sentry {` is placed. If I remove the sentry section, then it syncs w/o problems.

The error message is really weird. Can you try to clean (i.e. remove the `build` folder) and build again?

**Comment by marandaneto** [comment]
@mkilmanas since this is another issue, please raise a new issue with the code snippet of your full setup and if its a groovy or kts gradle file, so we can debug it, thanks
