### ISSUE TITLE
Cannot run r8 after adding Sentry Gradle Plugin

### ISSUE THREAD

**Issue by ansman** [getsentry/sentry-android-gradle-plugin#228]
_Android Gradle Plugin:_
**7.1.0-beta02**

_Gradle:_
**7.2**

_Optimizer:_
- [ ]  ProGuard
- [X]  R8

_Have you created the sentry.properties file?_
- [X]  Yes -> where? `/sentry.properties`
- [ ]  No

---
I have the following issue:

We have been using our own gradle plugin for Sentry but are switching to the official one right now. After migrating we can no longer minify our app as it fails with this error:
```
Execution failed for task ':app:minifyReleaseWithR8'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Failed to transform work-runtime-2.5.0.aar (androidx.work:work-runtime:2.5.0) to match attributes {artifactType=android-asm-instrumented-jars, asm-transformed-variant=internal, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AsmClassesTransform: /Users/nicklas/.gradle/caches/transforms-3/54dca5c2bcc42347fc969b1bf4683fe8/transformed/work-runtime-2.5.0-runtime.jar.
         > java.lang.NullPointerException (no error message)
```
Simply uncommenting the adding of the Sentry plugin makes the minify task work again so it's definitely related to Sentry.

**Comment by ansman** [comment]
Disabling `tracingInstrumentation` seems to fix it.

**Comment by marandaneto** [comment]
@ansman which version of the SAGP?

@romtsn please have a look at it

**Comment by ansman** [comment]
This was on `3.0.0-beta.1`

**Comment by romtsn** [comment]
@ansman thanks a lot for trying this out, this is new functionality which involves bytecode manipulation - we do that for automatic Room queries performance measurement. This is likely caused by us doing something wrong - do you use Room directly in your app? Or WorkManager?

Also, if you have some spare time, could you enable debug output via `tracingInstrumentation.debug = true` and then share what is under `build/tmp/sentry` folder with us, e.g. as a zip archive? This would help us a lot! There's no private data shared, just the bytecode instrumentation output. If you're not allowed, a simple screenshot of the contents of that folder would also help.

Thank you!

**Comment by ansman** [comment]
Of course!

We are using Work Manager but not Room.

Here is the logs: [sentry.zip](https://github.com/getsentry/sentry-android-gradle-plugin/files/7499854/sentry.zip)

**Comment by romtsn** [comment]
Thanks a bunch! I will look into this and try to resolve it for the next release asap

**Comment by romtsn** [comment]
@ansman and one more request (sorry, if it's too many) - could you also share with us the actual jar from this path? 

```
/Users/nicklas/.gradle/caches/transforms-3/54dca5c2bcc42347fc969b1bf4683fe8/transformed/work-runtime-2.5.0-runtime.jar.
```

I'd like to decompile it and see what went wrong there

**Comment by romtsn** [comment]
@ansman tried to reproduce it with your versions but no luck... I guess I'd need to look at that broken artifact/jar as mentioned above. It'd also help if you post the gradle command that you are running your build with.

**Comment by romtsn** [comment]
Figured out, the bug is caused by applying both our plugin and the [Firebase Performance gradle plugin](https://firebase.google.com/docs/perf-mon/get-started-android). The firebase one overwrites some flags for bytecode instrumentation, that we are relying on - for now I am not sure if we should take any action, but I filed an [issue](https://issuetracker.google.com/issues/205873414) for Google. After they clarify whether it's expected behavior or not we'll come back to this issue. 

The workaround for now is to either get rid of the firebase-perf plugin or disable `tracingInstrumentation.enabled = false`
