### ISSUE TITLE
Feature request: gradle plugin support for android library projects

### ISSUE THREAD

**Issue by amir169** [getsentry/sentry-android-gradle-plugin#3]
We want to use sentry in an android library project. We followed this documentation <https://docs.sentry.io/clients/java/modules/android/> and it seems to work fine if we just init Sentry inside our library but we failed to use gradle plugin for Proguard files.

Is there any way to send Proguard mapping of an android library to Sentry?

**Comment by mrbar42** [comment]
this issue still hasn't been resolved.
When running gradle with `com.android.library` and not `com.android.application` an error is thrown in [this](https://github.com/getsentry/sentry-android-gradle-plugin/blob/164515cba16e6f2b33d5410ebe97fde68b6af294/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy#L220) line since `applicationVariants` doesn't exist and instead `libraryVariants` should be used.

The error:
```
Could not get unknown property 'applicationVariants' for object of type com.android.build.gradle.LibraryExtension.
```

also reported [here](https://github.com/getsentry/sentry/issues/14454)

**Comment by twanschik** [comment]
Hi,
to get around the problem you can basically add the "sentry-debug-meta.properties" file to the assets folder of your library and use `consumerProguardFiles` to keep apps from obfuscating your lib.

Here is what I did to get it running:

- create a "consumer-proguard-rules.pro" file:

```
# keep apps from obfuscating the lib

-keep class package.path.of.your.lib.** { *; }
-dontwarn package.path.of.your.lib.**
```

- build the library (including the typical proguardFiles rules to obfuscate the library)
- use the sentry-cli to upload the Proguard mappings to the sentry server:

`sentry-cli upload-proguard "path\to\your\lib\build\outputs\mapping\release\mapping.txt" -o ORANIZATION_NAME -p PROJECT_NAME --write-properties "path\to\your\lib\src\main\assets\sentry-debug-meta.properties"`

This will automatically add the correct "sentry-debug-meta.properties" file to the lib`s assets folder

- publish the library including the correct "sentry-debug-meta.properties" in the assets folder of the library.

At the end you will have published a library that is obfuscated but won't get obfuscated by apps.

The only downside is that apps cannot use sentry itself because this would lead to overwriting the "sentry-debug-meta.properties" file of your library.

**Comment by arunshankar87** [comment]
Any reason this has not been taken up to support libraries?

**Comment by nikiizvorski** [comment]
> Hi,
> to get around the problem you can basically add the "sentry-debug-meta.properties" file to the assets folder of your library and use `consumerProguardFiles` to keep apps from obfuscating your lib.
> 
> Here is what I did to get it running:
> 
> * create a "consumer-proguard-rules.pro" file:
> 
> ```
> # keep apps from obfuscating the lib
> 
> -keep class package.path.of.your.lib.** { *; }
> -dontwarn package.path.of.your.lib.**
> ```
> 
> * build the library (including the typical proguardFiles rules to obfuscate the library)
> * use the sentry-cli to upload the Proguard mappings to the sentry server:
> 
> `sentry-cli upload-proguard "path\to\your\lib\build\outputs\mapping\release\mapping.txt" -o ORANIZATION_NAME -p PROJECT_NAME --write-properties "path\to\your\lib\src\main\assets\sentry-debug-meta.properties"`
> 
> This will automatically add the correct "sentry-debug-meta.properties" file to the lib`s assets folder
> 
> * publish the library including the correct "sentry-debug-meta.properties" in the assets folder of the library.
> 
> At the end you will have published a library that is obfuscated but won't get obfuscated by apps.
> 
> The only downside is that apps cannot use sentry itself because this would lead to overwriting the "sentry-debug-meta.properties" file of your library.

I am having the same issue. Currently and followed the steps. It seems's doesn't work for me at this stage using Sentry-CLI to upload the mapping. And i also have the rules for the application that used my module. Do i need to wait a bit or only further issues will be de-obfuscated. I can see the sentry properties in the folder and maybe i should update my mapping once again.

**Comment by marandaneto** [comment]
See the linked issue https://github.com/getsentry/sentry-docs/issues/3611
this is going to be closed as `wont fix`

**Comment by marandaneto** [comment]
> I am having the same issue. Currently and followed the steps. It seems's doesn't work for me at this stage using Sentry-CLI to upload the mapping. And i also have the rules for the application that used my module. Do i need to wait a bit or only further issues will be de-obfuscated. I can see the sentry properties in the folder and maybe i should update my mapping once again.
> 
> Do i need to close all the previous issues in order to see the new ones? Since i haven't closed them but i can see them being updated?
> 
> Maybe that's my issue.

this is not a bug though, the final App will redo the obfuscation anyway, this is how the Android Gradle plugin tooling works (R8/Proguard)

**Comment by nikiizvorski** [comment]
So currently i have this: 

if io.module class is obfuscated to a.b.c then the mappiung file a.b.c -> io.module should work

And the actual mapping is correct it's uploaded but then doesn't seem to be detected i have all the above and it only works if i keepclass names.

Do you have any suggestion on that?

Thanks

**Comment by marandaneto** [comment]
closing in favor of https://github.com/getsentry/sentry-docs/issues/3611
