### ISSUE TITLE
Your advertising ID declaration in Play Console says that your app uses advertising ID

### ISSUE THREAD

**Issue by hanwoo-kim** [getsentry/sentry-android-gradle-plugin#547]
### Gradle Version

7.4

### AGP Version

7.3.1

### Code Minifier/Optimizer

R8

### Version

3.12.0

### Sentry SDK Version

6.28.0

### Steps to Reproduce

1. Generate Signed Bundle
2. Create release in Play console with the generated aab.

### Expected Result

should move to next step(review) without error message as we don't use advertising id

### Actual Result

It's showing this message as a result of the uploading aab, but we don't use 

![Screen Shot 2023-08-24 at 3 50 38 PM](https://github.com/getsentry/sentry-android-gradle-plugin/assets/143058321/bc4e2dc2-1713-433e-ae95-cd97a6f69294)

**Comment by romtsn** [comment]
hi @hanwoo-kim, why do you think Sentry is the cause here? We do not declare advertising id nor do we have any dependency on the google play service nor do we declare any relevant permissions. We would need more information to understand why you concluded our SDK is the cause here.

Maybe this thread can give you answers? https://stackoverflow.com/questions/71473553/action-requested-declare-your-ad-id-permission

**Comment by markushi** [comment]
@hanwoo-kim Did you have any chance to look into this?

**Comment by hanwoo-kim** [comment]
Hi @romtsn @markushi , sorry for that I didn't give you the enough information for the issue why I thought so and late reply.

Long story short: turns out the issue was not coming from the Sentry SDK, so I'll close this issue ticket.

First of all, we were using Crashlytics and decided to change it to use Sentry, so I removed all the libraries and codes that related to the Firebase Crashlytics and added Sentry, and then tried to deploy to Google Play console, and it showed the error message about AD_ID permission. That's why I was thinking it's from Sentry SDK as I didn't change/add any other library.
Yesterday, I tried to deploy the app without Sentry and Crashlytics, and it showed same AD_ID permission error message!
That's very weird.
1. with Crashlytics only -> OK
2. with Sentry, w/o Crashlytics -> ERROR
3. w/o Sentry, w/o Crashlytics -> ERROR(???)

I tried several times(rebuild after cleaning build folder, invalidating caches....), but the results were same.
Also tried the some solution such as the answer from stackoverflow you've shared(thanks!), but no luck.
Something weird is going on but I couldn't understand.
I'm going to make some more trials, but it's definitely not from Sentry, so I'll close this ticket.

By the way, it would be great if you can add this construction in your installation guide for Android.
adding sentry.properties with
```
defaults.project=your-project
defaults.org=your-org
auth.token=YOUR_AUTH_TOKEN

```

I was struggling with this error on gradle build "app:uploadSentryProguardMappingsRelease"
`An organization slug is required (provide with --org)`

I'm not sure if you added a construction about this in somewhere in your installation guide, but I couldn't find it and spent time to figure out this build error, so it would be nice if it's on the same page as additional step for those who are using proguard obfuscating in their Android app project.

Thanks!

**Comment by romtsn** [comment]
> By the way, it would be great if you can add this construction in your installation guide for Android.
adding sentry.properties with

We've recently revamped our onboarding docs, and it's now linked directly after you set up the SDK:
<img width="597" alt="image" src="https://github.com/getsentry/sentry-android-gradle-plugin/assets/4999776/646109af-da3b-47da-ab88-2508af9e3522">
Plus, it's also available on the [docs](https://docs.sentry.io/platforms/android/configuration/gradle/?original_referrer=https%3A%2F%2Fdocs.sentry.io%2Fplatforms%2Fandroid%2F#proguardr8--dexguard). 

> with Crashlytics only -> OK

I think it's working with Crashlytics because they declare the permission on their SDK and then it gets merged with your app's manifest and that's why it works. But perhaps there's some other dependency (or your app) that uses [AdvertisingId](https://developers.google.com/android/reference/com/google/android/gms/ads/identifier/AdvertisingIdClient) from play-services, and that does not declare the necessary permission
