### ISSUE TITLE
Access to 'ignoredBuildTypes' exceeds its access rights

### ISSUE THREAD

**Issue by sryze** [getsentry/sentry-android-gradle-plugin#645]
### Gradle Version

8.2

### AGP Version

8.2.2

### Code Minifier/Optimizer

None

### Version

4.2.0

### Sentry SDK Version

7.2.0

### Steps to Reproduce

Add this to build.gradle:

```
sentry {
    ignoredBuildTypes = ['debug']
}
```

as per [documentation](https://docs.sentry.io/platforms/android/configuration/gradle/#variant-filtering).

### Expected Result

Expected to compile without warnings

### Actual Result

Android Studio shows a warning: `Access to 'ignoredBuildTypes' exceeds its access rights`

![Screenshot from 2024-01-29 22-15-29](https://github.com/getsentry/sentry-android-gradle-plugin/assets/4525736/f07973ca-6629-486d-b552-43015614db06)

Same for `ignoredFlavors` and `ignoredVariants`.

**Comment by romtsn** [comment]
hey, this turns out to be an IDEA/AS bug, that still hasn't been fixed: https://youtrack.jetbrains.com/issue/IDEA-270236/Managed-properties-DSL. The problem seems to be Kotlin/Groovy interop not working well.

I think you can workaround it by removing the equal sign for now:
```
sentry {
    ignoredBuildTypes ['debug']
}
```

But I'm gonna close this issue as the underlying problem is on the IDE side, hoping they will fix it soon (and it's just a warning, the build is still executing fine). Thanks for reporting!
