### ISSUE TITLE
Update TestNG Version to avoid Security Vulnerabilities 

### ISSUE THREAD

**Issue by inktomi** [getsentry/sentry-android-gradle-plugin#663]
### Gradle Version

8.6

### AGP Version

8.2.2

### Code Minifier/Optimizer

R8

### Version

4.3.0

### Sentry SDK Version

7.4.0

### Steps to Reproduce

Include the gradle plugin, then run your build in an environment that blocks libaries with known CVE issues. 

### Expected Result

Build succeeds because no versions of libraries contain known CVEs.

### Actual Result

CVE-2022-4065 is found because of TestNG 7.5

**Comment by romtsn** [comment]
hi @inktomi this was a regression that added unwanted dependencies to the build classpath, which got fixed in https://github.com/getsentry/sentry-android-gradle-plugin/pull/660. We're going to release a new version of the gradle plugin tomorrow CET time with this fixed included. I'll keep you posted, but gonna close this issue as it's been already adressed. Thank you for the report!

**Comment by inktomi** [comment]
I was out, but I'll try it today and report back!

**Comment by romtsn** [comment]
apparently this didn't fix it, I'll take another look soon, see https://github.com/getsentry/sentry-android-gradle-plugin/issues/656#issuecomment-1977519631
