### ISSUE TITLE
Improve Gradle integration documentation (sentry.properties)

### ISSUE THREAD

**Issue by gleno** [getsentry/sentry-android-gradle-plugin#8]
I was following
https://docs.sentry.io/platforms/android/#gradle-integration

and nowhere it said anything about sentry.properties file. I found that in some blogpost. Maybe the docs should be updated.

For anyone like me, apparently there's supposed to be a `sentry.properties` file in your apps root, and it should have:

```
defaults.project=myproject
defaults.org=myorg
auth.token=07fb331_______API_KEY_FROM_SITE/API_____123c05d7d
```

Note that there are no quotes around anything.

**Comment by marandaneto** [comment]
hey @gleno thanks for your message and sorry for that.

yes, definitely we should improve that, thanks for the tip.
the documentation of the old Sentry Android SDK explains a bit more about it and may be seen here https://docs.sentry.io/clients/java/integrations/#gradle-integration

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-docs/pull/1847

**Comment by filipatbnp** [comment]
still - I dont see anything about "Sentry plugin reads only root directory sentry.properties"

please update the docs!

**Comment by romtsn** [comment]
hi @filipatbnp, I think this was an issue for the old version of the gradle plugin. Since v2 it should be capable of finding `sentry.properties` whenever they are, see here: https://github.com/getsentry/sentry-android-gradle-plugin/blob/7f8d942429f336d9be5452bd6ac3449f655267f2/plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPropertiesFileProvider.kt#L19-L65
